### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by jake-101** [digitoimistodude/image-user-feed#1]
It looks like it worked on my desktop dev env but not on the actual server. does it still work for you?

**Comment by craigbarlow** [comment]
> It looks like it worked on my desktop dev env but not on the actual server. does it still work for you?

I've got the exact same thing happening to me, did you manage to resolve this?

**Comment by jake-101** [comment]
Yes, but I rewrote the dude feed plugin to use IGs new graphql API
